
wifi:
  ssid: "treppenhaus"
  password: "X07614760498"
  manual_ip:
    gateway: 192.168.1.2

esphome:
  comment: "ABL eMH1 Charger via RS485/Modbus-ASCII"
  compile_process_limit: 1

packages:
  device-base: !include
    file: common/esp32-base.yaml
    vars:
      area: "Utility wing"
      esp_name: "ev-charger"
      friendly_name: "EV charger"
      #static_ip: 10.5.5.78
      static_ip: 192.168.1.11

external_components:
  source:
    type: git
    url: https://github.com/jougs/esphome-abl-emh1
    ref: main
  refresh: 30s

uart:
  id: uart_2
  baud_rate: 38400
  tx_pin: 19
  rx_pin: 18
  parity: EVEN

emh1_modbus:
    uart_id: uart_2
    id: modbus0

abl_emh1:
  emh1_modbus_id: modbus0
  update_interval: 5s

preferences:
  flash_write_interval: 5min

text_sensor:
  - platform: abl_emh1
    mode:
      name: "Status"
    serial_number:
      name: "Serial number"
      disabled_by_default: true

sensor:
  - platform: abl_emh1
    max_current:
      name: "Max current"
      state_class: "measurement"
      id: max_current
      disabled_by_default: true 
      accuracy_decimals: 0
    en1_status:
      name: "EN1 status"
      disabled_by_default: true 
    en2_status:
      name: "EN2 status"
      disabled_by_default: true 
    duty_cycle_reduced:
      name: "Reduced Duty Cycle (max_current)"
      disabled_by_default: true 
    ucp_status:
      name: "EV Connected (UCP <= 10V)"
    outlet_state:
      name: "Outlet state"
      disabled_by_default: true
      id: outlet_state
  - platform: uptime
    name: Uptime Sensor
    id: abl_uptime
    update_interval: 15s

number:
  - platform: template
    name: "Max Amps"
    id: set_current
    icon: mdi:arrow-oscillating
    min_value: 6
    max_value: 16
    step: 1
    optimistic: false
    lambda: 'return std::lround(id(max_current).state);'
    update_interval: 10s
    set_action:
      lambda: |-
        ESP_LOGD("main", "Sending modbus value = %d", (int)std::lround(x));
        id(modbus0)->send_current(std::lround(x));

switch:
  - platform: template
    name: "Enable"
    id: enable_switch
    icon: "mdi:power"
    lambda: 'return (id(outlet_state).state != 0xE0);'
    turn_off_action: 
      - lambda: |-
          if ((id(abl_uptime).state > 10.0) && (id(outlet_state).state != NAN)) 
            id(modbus0)->send_enable(0);
    turn_on_action: 
      - lambda: |-
          if ((id(abl_uptime).state > 10.0) && (id(outlet_state).state != NAN))
            id(modbus0)->send_enable(1);

select:
  - platform: template
    name: "EV Charge Mode"
    options:
      - "Solar only"
      - "Grid fast"
      - "Grid slow"
    optimistic: true
    icon: mdi:power-plug-battery
    set_action:
      - logger.log:
          format: "Charge mode changed to: %s"
          args: [x.c_str()]